services:
  db:
    image: mysql:8.0
    container_name: mysql_payload
    restart: always
    environment:
      MYSQL_DATABASE: payload_analyser
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: qradar_ticket
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=payload_analyser
    ports:
      - "5000:5000"
    volumes:
      - ..:/app

  nginx:
    image: nginx:latest
    container_name: nginx_front
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  mysql_data:
