services:
  # Base de données MySQL
  db:
    image: mysql:8.0
    container_name: mysql_payload
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payload_analyser
      TZ: Europe/Paris
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Ollama - Service d'IA locale optimisé SOC
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_soc
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # ChromaDB - Base de données vectorielle
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    restart: always
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    volumes:
      - chromadb_data:/chroma/chroma
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Retriever + FastAPI
  retriever:
    build:
      context: ./retriever
      dockerfile: Dockerfile
    container_name: mistral_retriever
    depends_on:
      - db
      - chromadb
      - ollama
    ports:
      - '5001:5000'
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=payload_analyser
      - OLLAMA_URL=http://ollama:11434
      - CHROMA_URL=http://chromadb:8000
      - MISTRAL_URL=http://ollama:11434
      - MISTRAL_LEARNER_URL=http://ollama:11434
    volumes:
      - retriever-data:/data
    restart: always

  # Application Web Flask
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: qradar_ticket
    restart: always
    depends_on:
      - db
      - retriever
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=payload_analyser
    ports:
      - "5000:5000"
    volumes:
      - profile_photos:/app/profile_photos

volumes:
  mysql_data:
  profile_photos:
  retriever-data:
  chromadb_data:
  ollama_data:
